version: "3.5"
services:
  sls-service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - postgres

  postgres:
    image: postgres:14.5-alpine
    ports:
      - "5432:5432"
    restart: always
    environment:
     - POSTGRES_PASSWORD=mysecretpassword
#    volumes:
#      - ./db-data/postgres/:/var/lib/postgresql/data
